# Generated by Django 2.1.2 on 2018-10-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adopcion',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idAdopcion')),
                ('fecha', models.CharField(max_length=20, verbose_name='fecha')),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idComuna')),
                ('descripcion', models.CharField(max_length=30, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idEstado')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idImagen')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='perro',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idPerro')),
                ('descripcion', models.CharField(max_length=30, verbose_name='descripcion')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.estado')),
                ('idImagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='raza',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idRaza')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idRegion')),
                ('descripcion', models.CharField(max_length=30, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='sexo',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idSexo')),
                ('descripcion', models.CharField(max_length=30, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idTipoUsuario')),
                ('descripcion', models.CharField(max_length=30, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='tipoVivienda',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idTipoVivienda')),
                ('descripcion', models.CharField(max_length=30, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False, verbose_name='idUsuario')),
                ('usuario', models.CharField(max_length=30, verbose_name='user')),
                ('idComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.comuna')),
                ('idRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.region')),
                ('idSexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.sexo')),
                ('idTipoVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.tipoVivienda')),
            ],
        ),
        migrations.AddField(
            model_name='perro',
            name='idRaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.raza'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.region'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='IdPerro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.perro'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misperris.usuario'),
        ),
    ]
