# Generated by Django 2.1.2 on 2018-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misperris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='nombrePerro',
            field=models.CharField(default='nn', max_length=30),
        ),
    ]
