# Generated by Django 2.1.2 on 2018-10-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Misperris', '0004_auto_20181025_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='imagen',
            new_name='imagenPerro',
        ),
    ]
