# Generated by Django 2.1.2 on 2018-10-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misperris', '0007_usuario_passa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='correo', max_length=30, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='rut', max_length=30, verbose_name='rut'),
        ),
    ]
