# Generated by Django 2.1.2 on 2018-10-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Misperris', '0008_auto_20181026_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idTipoUsuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Misperris.tipoUsuario'),
        ),
    ]
