# Generated by Django 2.1.2 on 2018-10-27 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Misperris', '0009_usuario_idtipousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idTipoUsuario',
            new_name='idTipoUser',
        ),
    ]
