# Generated by Django 2.1.2 on 2018-10-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Misperris', '0010_auto_20181027_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idTipoUser',
            new_name='idTipoUsuario',
        ),
    ]
