# Generated by Django 2.1.2 on 2018-10-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misperris', '0011_auto_20181027_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='imagenPerro',
            field=models.FileField(upload_to='perros/'),
        ),
    ]
