# Generated by Django 2.1.2 on 2018-10-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misperris', '0012_auto_20181028_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='imagenPerro',
            field=models.FileField(upload_to='perros/static/core/css/img'),
        ),
    ]
